### PR TITLE
Basic Angular set up 

### LINKED ISSUE #18: Set up the repository with basic  angular files
## Description
As a user,
I need set up the repository,
so that I can restart the project with angular framework

## Acceptance Criteria
- Basic working Angular App
- Basic files and modules established 

### Update [Required]
- README
- Create multiple new files

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour
Can I be assigned this issue @Tharangi  @divyanshu-rawat @Janiceilene @MeepyMay ?

### PR DESCRIPTION
**Pull request by anumehaagrawal**
### Description
In this PR I have set up the basic repository with packages and dependencies . i have also added the basic angular files

Fixes #18  

### Type of Change:
Primary Set up for new development environment

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I have tested it by running it on local host
### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sara-02** [comment]
@anumehaagrawal is this running in production, or do we currently have any users on it?
If not, then we can commit one folder at a time. Even though sending it separately will break the build for some time, but if create a PR and merge it continuously, we should be able to keep things as updated as possible.

**Comment by sara-02** [comment]
@anumehaagrawal It is not even displaying the folder list. Can you run the tree command, and ls command on this, and share the output. In the form of the gist.

**Comment by anumehaagrawal** [comment]
@sara-02 you mean folder list for the repo right ? I didnt understand exactly what you mean

**Comment by sara-02** [comment]
Yes. what I meant was this
https://www.geeksforgeeks.org/tree-command-unixlinux/ :)

**Comment by anumehaagrawal** [comment]
https://gist.github.com/anumehaagrawal/20fa062f997ed86bbdac3e850ea3a560 Here it is :)

**Comment by sara-02** [comment]
Cools. Lets try to break it. Until we create all the small PRs and have them merged, you can keep this PR open and mark this as a Work-In-Progress tag[WIP]

**Comment by anumehaagrawal** [comment]
I missed out the gitignore file , thats why so many files
 ..Ill add one and commit

**Comment by sara-02** [comment]
@anumehaagrawal sure, do that and then if the files are still large in number we will break it, else keep it as it is.

**Comment by anumehaagrawal** [comment]
Yeah sure :)

**Pull request closed without merging**
