### PR TITLE
Contact Page completed 

### PR DESCRIPTION
**Pull request by anumehaagrawal**
### Description
In this PR I have added  a fully functional contact form
Fixes #31 

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)

**Time Taken**
25 hours

### CODE REVIEW

**Comment by Tharangi** [comment]
1. Remove the 'Contact Us' header. 
2. Reduce the font size of 'Name', 'Email', 'Questions or Comments' labels. 
3. Remove the question mark(?) in 'Questions or Comments?' field.
4. Move the 'Send' button to the right side. 
screen shot 2018-06-07 at 10 19 27 pm

**Comment by Tharangi** [comment]
**Suggestion:** Since the buttons on the top are also centered now, isn't it nice to center align the form too? What do you think @kanmodi?

**Comment by kanmodi** [comment]
I think it'll look good both ways. If it's centered, it'll look symmetric but I'm more inclined towards the conventional button on the right side :P

**Comment by anumehaagrawal** [comment]
@Tharangi  I have made the UI changes as suggested

**Comment by Tharangi** [comment]
This looks very different now! :p @kanmodi 
screen shot 2018-06-09 at 9 37 40 pm

@anumehaagrawal: I hope you didn't misinterpret the suggestion I gave to center align the form. I didn't mean to center align the labels too!! 

Also, @anumehaagrawal Could you please, 
Remove the question mark(?) in 'Questions or Comments?' field and if you could reduce the font-size also a bit.

**Comment by kanmodi** [comment]
Center-aligned looks pretty neat too :)

**Comment by anumehaagrawal** [comment]
@Tharangi  I will reduce the font size :) 
@kanmodi  Should I continue with this center align or left align the labels ?

**Comment by Tharangi** [comment]
I prefer left aligning! I guess @kanmodi is fine with center aligning too. Anyways I will merge this. We can get feedback from others as well and finalize the UI changes later.

**Pull request merged**
