### PR TITLE
Uniform height of sliders throughout pages

### LINKED ISSUE #68: Keep the space between the slideshows/ header image and the content in all the pages similar
## Description
As a Systers community member,
I need to see the space between the slideshows/ header image and the content in all the pages similar,
so that I can have a better user experience.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] home.component.html
- [ ] communities.component.html
- [ ]  contact.component.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by anumehaagrawal**
### Description
In this PR I have maintained constant height for all sliders
Fixes #68 #66 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
This has been tested by running it on local host

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by anumehaagrawal** [comment]
@Tharangi  Yeah Im working on it , Id need some help in it :)

**Comment by Rupinderwadali** [comment]
@anumehaagrawal I had suggested you methods for solving this issue. Are you still facing any issue?

**Comment by anumehaagrawal** [comment]
@Rupinderwadali  I have changed this in the margin-patch and added vh as you suggested :)

**Comment by anumehaagrawal** [comment]
@Rupinderwadali  I have changed this in the margin-patch and added vh as you suggested :)

**Pull request merged**
