### PR TITLE
Fix slider height

### LINKED ISSUE #37: Fix the slider height in the Communities page
## Description
As a Systers community member
I need to see the slider with a proper height
so that I can have a better user experience

## Mocks
screenshot from 2018-06-04 21-15-31

### Update [Required]
- [ ] communities.component.html
- [ ]  communities.component.ts

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours 
@Tharangi  @kanmodi  Can you assign me this ?

### PR DESCRIPTION
**Pull request by anumehaagrawal**
### Description
In this PR I have fixed the slider height so that it doesnt exceed the view on scrolling
Fixes #37 

### Type of Change:
- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by Tharangi** [comment]
Card responsiveness issue seems to be still remaining though. 

screen shot 2018-06-05 at 9 46 17 pm
screen shot 2018-06-05 at 9 48 04 pm

**Comment by anumehaagrawal** [comment]
screenshot from 2018-06-06 00-50-29
@Tharangi  Fixed this :)

**Comment by kanmodi** [comment]
Did you try 4 cards in a row?

**Comment by Tharangi** [comment]
@kanmodi : Yes she has done it an has sent another PR on that.

**Comment by Tharangi** [comment]
Closing this PR as these changes were merged with PR #40.

**Pull request closed without merging**
