### PR TITLE
Contact us Page modified

### LINKED ISSUE #48: Add Join us section in contact page
## Description
As a user
I need add a join us section along with contact form

## Mocks
screenshot from 2018-06-13 19-31-04

### Update [Required]
- [ ] contact.component.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours 
@Tharangi  @kanmodi  Can you assign me this issue ?

### PR DESCRIPTION
**Pull request by anumehaagrawal**
### Description
In this PR I have added the join us section in the contact us page

Fixes #48 

### Type of Change:
- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
This PR has been tested by running it on local host

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Tharangi** [comment]
Maybe the UI could be improved more. Also, better if the 'Join Us' links open in a new tab. Let's confirm with others also on those at next meeting.

**Comment by anumehaagrawal** [comment]
@Tharangi  could you suggest UI changes ? And what has been decided about tabs ?

**Comment by anumehaagrawal** [comment]
@Tharangi  I checked out the links from the minutes of the meet , I will try to implement one of that

**Comment by Tharangi** [comment]
@anumehaagrawal: We thought of creating a newcomers issue to create UI for the Contact Us page, but you also can try something similar to what is suggested in the meeting notes as a stretch goal later. Also, your Contact Us page and what @BaaniLeen is doing for Systers.io should have similar components/ icons. 
Therefore, for the moment,
**Join Us**
1. Remove the 'at' from 'Join Us at'.
2. Increase the space between icons and the wording. 
3. Put equal-sized icons in 'Join Us'. 
4. [OPTIONAL] Put colored icons. 
**Contact Us Form**
1. Put send button to the right side.

**Comment by kanmodi** [comment]
Feedback has been incorporated, right? Shall we merge this @Tharangi ?

**Comment by Tharangi** [comment]
Still the 'Send' button is on the left side and the icons are not equal-sized. Since we are planning to go for a UI change in this page again, let's merge this. Anyways good work @anumehaagrawal !
screen shot 2018-06-18 at 10 39 48 pm

**Pull request merged**
