### PR TITLE
Uploaded images for communities

### LINKED ISSUE #73: UI Update/CleanUp for GSoC18
## Description
As a developer,
I need to complete the branding of the app,
so that I can push a final product to production.

## Mocks

-

-

-

-

-

### Update [Required]
- [90%] Navbar updated to white buttons on the top right, with blue on hover, and underline on active.
- [ ] Footer updated to three links on the right: [Code of Conduct](https://ghc.anitab.org/code-of-conduct/), [Terms & Conditions](https://anitab.org/terms-of-use/), and [Privacy Policy](https://anitab.org/privacy-policy/)
- [ ] Footer remove "Contact Us" and the "We connect" statement.
- [ ] Remove blue footer and update to 
image

- [ ] Headers updated to ---
- [ ] Sub-headers updated to ---
- [ ] Text updated to ---
- [ ] Buttons updated to ---

- [ ] Update favicon to [32x32 png](https://anitab.org/wp-content/assets/images/favicons/favicon-32x32.png) on desktop, [16x16 png](https://anitab.org/wp-content/assets/images/favicons/favicon-16x16.png) on mobile/tablet.

### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
8 hours

### PR DESCRIPTION
**Pull request by anumehaagrawal**
### Description
In this PR I have added images for communities

Fixes #73 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
This has been tested by running it on local host.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by anumehaagrawal** [comment]
@Tharangi  okay lets see how we can make them clear . And i havent added images below because I just had those 4-5 images which were given but Ill add dummy images for the rest

**Comment by Tharangi** [comment]
Yeah, let's add some dummy images for the moment since it doesn't look good otherwise.

**Comment by anumehaagrawal** [comment]
@Tharangi  Done added :)

**Comment by Tharangi** [comment]
Please follow what @Rupinderwadali has suggested and see to resolve the image issue. So that we could merge this.

**Pull request merged**
